forum/forum/common/urls.py
from django.urls import path

from forum.common.views import (
    create_category_view,
    create_post_view,
    delete_category_view,
    index_view,
    post_delete_view,
    register_view,
    topic_create_view,
    topic_posts_view,
    topic_list_view,
    update_category_view,
    update_topic_view,
    block_topic_view,
)


app_name = 'common'

urlpatterns = [
    path('', index_view, name='index'),
    path('category/create', create_category_view, name='create_category'),
    path('category/delete/<int:pk>', delete_category_view, name='delete_category'),
    path('category/update/<int:pk>', update_category_view, name='update_category'),
    path('topics/<int:pk>', topic_list_view, name='topics'),
    path('topic/create/<int:pk>', topic_create_view, name='create_topic'),
    path('topic/posts/<int:pk>', topic_posts_view, name='topic_posts'),
    path('create/post/<int:pk>', create_post_view, name='create_post'),
    path('post/delete/<int:pk>', post_delete_view, name='delete_post'),
    path('topic/update/<int:pk>', update_topic_view, name='update_topic'),
    path('topic/block/<int:pk>', block_topic_view, name='block_topic'),

    path('register', register_view, name='register'),
]

forum/forum/urls.py
from django.urls import path, include


urlpatterns = [
    path('', include('forum.common.urls')),
    path('', include('django.contrib.auth.urls')),
]

forum/forum/common/models.py
from gettext import gettext as _

from django.contrib.auth import get_user_model
from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(
        _('Category name'),
        max_length=16,
        validators=[
            MinLengthValidator(3, _('Category name to short.')),
        ]
    )
    order_number = models.PositiveIntegerField(
        _('Order number'),
        default=0,
    )

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ['-order_number']

    def __str__(self):
        return self.name


class Topic(models.Model):
    name = models.CharField(
        _('Topic'),
        max_length=128,
        validators=[
            MinLengthValidator(12),
        ]
    )
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(
        _('Active'),
        default=True,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
        blank=False,
        null=False,
    )

    class Meta:
        """ Meta class """
        verbose_name = _('Topic')
        verbose_name_plural = _('Topics')
        ordering = ['-created_at']

    def __str__(self):
        return slugify(self.name)


def get_or_create_deleted():
    """ Get deleted user  """
    return get_user_model().objects.get_or_create(name='Erased')[0]


class Post(models.Model):
    """ Post model """
    text = models.TextField(_('Text'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        blank=False,
        null=False
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.SET(get_or_create_deleted),
        null=True,
        blank=False
    )

    class Meta:
        """ Meta class """
        verbose_name = _('Post')
        verbose_name_plural = _('Posts')
        ordering = ['created_at']

forum/forum/common/forms.py
from django.forms import (
    CharField,
    EmailField,
    ModelForm,
)
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from forum.common.models import (
    Category,
    Post,
    Topic,
)


class CategoryCreateForm(ModelForm):
    """ Create category form """

    class Meta:
        """ Meta class """
        model = Category
        fields = ['name', 'order_number']


class BlockTopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['active']


class PostForm(ModelForm):
    """ Create post form """

    class Meta:
        """ Meta class """
        model = Post
        fields = ['text']


class TopicForm(ModelForm):
    """ Create topic form """

    class Meta:
        """ Meta class """
        model = Topic
        fields = ['name']


class RegisterForm(UserCreationForm):
    """ User registration form """
    first_name = CharField(max_length=30, required=False, help_text='Optional.')
    last_name = CharField(max_length=30, required=False, help_text='Optional.')
    email = EmailField(max_length=128, help_text='Required.')

    class Meta:
        """ Meta class """
        model = get_user_model()
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

forum/forum/common/views.py
from typing import cast

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    FormView,
    ListView,
    UpdateView,
)

from forum.common.forms import (
    CategoryCreateForm,
    RegisterForm,
    PostForm,
    TopicForm,
    BlockTopicForm,
)
from forum.common.mixin import SuperUserMixin
from forum.common.models import (
    Category,
    Post,
    Topic,
)


class IndexView(ListView):
    model = Category


index_view = IndexView.as_view()


class CreateCategoryView(
    LoginRequiredMixin,
    SuperUserMixin,
    SuccessMessageMixin,
    CreateView
):
    model = Category
    form_class = CategoryCreateForm
    success_url = reverse_lazy('common:index')
    success_message = _('Category successfully created')


create_category_view = CreateCategoryView.as_view()


class DeleteCategoryView(
    LoginRequiredMixin,
    SuperUserMixin,
    SuccessMessageMixin,
    DeleteView
):
    model = Category
    success_url = reverse_lazy('common:index')
    success_message = _('Category successfully deleted')


delete_category_view = DeleteCategoryView.as_view()


class UpdateCategoryView(
    LoginRequiredMixin,
    SuperUserMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Category
    form_class = CategoryCreateForm
    success_url = reverse_lazy('common:index')
    template_name_suffix = '_update_form'
    success_message = _('Category successfully updated')


update_category_view = UpdateCategoryView.as_view()


class RegisterView(SuccessMessageMixin, CreateView):
    """ Create new user """
    form_class = RegisterForm
    success_url = reverse_lazy('common:index')
    template_name = 'registration/register.html'
    success_message = _('User successfully created')


register_view = RegisterView.as_view()


class TopicListView(ListView):
    """ List of topics from specified categories """
    model = Topic
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset """
        category_pk = self.kwargs['pk']
        return Topic.objects.filter(category_id=category_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Extend get context data """
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['category'] = Category.objects.get(id=self.kwargs['pk'])
        return context


topic_list_view = TopicListView.as_view()


class TopicCreateView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    """ Create new topic """
    model = Topic
    model2 = Post
    form_class = TopicForm
    form_class2 = PostForm
    template_name = 'common/topic_form.html'
    success_message = _('Topic created with success')
    success_url = reverse_lazy('common:index')

    def get_context_data(self, **kwargs):
        """ Extend default context """
        context = super().get_context_data(**kwargs)
        context['form2'] = self.form_class2()
        return context

    def post(self, request, *args, **kwargs):
        """ Extend post method """
        super().post(request, *args, **kwargs)
        form = self.form_class({'name': request.POST['name']})
        form2 = self.form_class2({'text': request.POST['text']})

        if form.is_valid() and form2.is_valid():
            with transaction.atomic():
                new_topic = self.model(
                    name=request.POST['name'],
                    category_id=self.kwargs['pk']
                )
                new_topic.save()
                first_post = self.model2(
                    text=request.POST['text'],
                    topic=new_topic,
                    author=request.user
                )
                first_post.save()
            return redirect(self.success_url)

        return render(request, self.template_name, {'form': form, 'form2': form2})


topic_create_view = TopicCreateView.as_view()


class TopicPostsView(ListView):
    """ List of posts from topic """
    model = Post
    form_class = PostForm
    paginate_by = 20

    def get_queryset(self):
        """ Override queryset """
        topic_pk = self.kwargs['pk']
        return Post.objects.filter(topic_id=topic_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Extend get context data """
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['topic'] = Topic.objects.get(id=self.kwargs['pk'])
        context['form'] = self.form_class()
        return context


topic_posts_view = TopicPostsView.as_view()


class CreatePostView(LoginRequiredMixin, CreateView):
    """ Create new post by authenticated user """
    model = Post
    form_class = PostForm
    success_message = _('Post created with success')

    def get(self, *args, **kwargs):
        """ Override method """
        return redirect(
            reverse('common:topic_posts', kwargs=kwargs)
        )

    def post(self, request, *args, **kwargs):
        """ Override method """
        form = self.form_class({'text': request.POST['text']})
        if not form.is_valid():
            messages.error(request, _('Incorrect data in post form!'))
            return redirect(
                reverse('common:topic_posts', kwargs=kwargs)
            )
        post = self.model(
            text=request.POST['text'],
            topic_id=kwargs['pk'],
            author=request.user
        )
        post.save()
        messages.success(request, self.success_message)
        return redirect(
            reverse('common:topic_posts', kwargs=kwargs)
        )


create_post_view = CreatePostView.as_view()


class PostDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Post
    success_message = _('Post deleted')

    def get_success_url(self) -> str:
        listed_object = self.get_object()
        return cast(str, reverse_lazy("common:topic_posts", kwargs={'pk': listed_object.topic.id}))

    def post(self, request, *args: str, **kwargs):
        post = self.get_object()
        if (request.user.id == post.author_id) or request.user.is_superuser:
            messages.success(request, self.get_success_message(cleaned_data={}))
            return super().post(request, *args, **kwargs)
        messages.error(request, _("Removing post not allowed!"))
        return redirect(self.get_success_url())

    def get(self, request, *args, **kwargs):
        post = self.get_object()
        if (request.user.id == post.author_id) or request.user.is_superuser:
            messages.success(request, self.get_success_message(cleaned_data={}))
            return super().get(request, *args, **kwargs)
        messages.error(request, _('Removing post not allowed!'))
        return redirect(self.get_success_url())


post_delete_view = PostDeleteView.as_view()


class UpdateTopicView(
    LoginRequiredMixin,
    SuperUserMixin,
    SuccessMessageMixin,
    UpdateView
):
    model = Topic
    form_class = TopicForm
    success_url = reverse_lazy('common:index')
    template_name_suffix = '_update_form'
    success_message = _('Topic successfully updated')


update_topic_view = UpdateTopicView.as_view()


class BlockTopicView(LoginRequiredMixin,
                     SuperUserMixin,
                     SuccessMessageMixin,
                     UpdateView):
    model = Topic
    form_class = BlockTopicForm
    template_name_suffix = '_block_form'
    custom_message = "Blocked"
    success_message = "Topic status active: %(active)s"

    def get_success_url(self) -> str:
        listed_object = self.get_object()
        return cast(str, reverse_lazy("common:topics", kwargs={'pk': listed_object.category.id}))

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            active=self.object.active,
        )


block_topic_view = BlockTopicView.as_view()

forum/forum/common/templates/common/base.html
{% extends 'bootstrap4/bootstrap4.html' %}

{% load bootstrap4 static i18n %}

{% block bootstrap4_title %}{% trans 'Python Academy Forum' %}{% endblock %}

<!-- Overwrite js extra panel -->
{% block bootstrap4_extra_head %}
    {% bootstrap_javascript jquery='full' %}
{% endblock %}

<!-- Overwrite place before content -->
{% block bootstrap4_before_content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Brand and toggle get grouped for better mobile display -->
    <a class="navbar-brand" href="{% url 'common:index' %}">{% trans 'Python Academy Forum' %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdow-toggle" href="#" id="profileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans 'Profile' %} {{ request.user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
                    </div>
                </li>
            {% else %}
                <li class='nav-item {% if "logout" in request.path %} active {% endif %}'>
                    <a class="nav-link" href="{% url 'login' %}">{% trans 'Login' %}</a>
                </li>
                <li class='nav-item'>
                    <a class="nav-link" href="{% url 'common:register' %}">{% trans 'Register' %}</a>
                </li>
            {% endif %}
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>
{% if messages %}
    {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
      </div>
    {% endfor %}
{% endif %}
{% endblock %}

{% block bootstrap4_content %}
<div class="container">
    <div class="row">
        <div class="col pt-5">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

forum/forum/common/templates/common/category_confirm_delete.html
{% extends 'common/base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>
        {% blocktrans with name=category.name %}Are you sure you want delete category {{ name }}{% endblocktrans %}
    </h1>
    <div class="d-none d-lg-block d-xl-block">
        {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger" %}
        <a href="{% url 'common:index' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
    </div>
    <div class="d-lg-none d-xl-none">
        {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger btn-lg btn-block" %}
        <a href="{% url 'common:index' %}" class="btn btn-light btn-lg btn-block">{% trans 'Cancel' %}</a>
    </div>
</form>
{% endblock %}

forum/forum/common/templates/common/category_form.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="d-none d-lg-block d-xl-block">
        {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
        <a href="{% url 'common:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
    </div>
    <div class="d-lg-none d-xl-none">
        {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
        <a href="{% url 'common:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
    </div>
</form>
{% endblock %}

forum/forum/common/templates/common/category_list.html
{% extends 'common/base.html' %}

{% load i18n %}

{% block content %}
{% if request.user.is_superuser %}
<div class="row pb-3">
    <div class="col">
        <a href="{% url 'common:create_category' %}" class="btn btn-primary">{% trans 'Create category' %}</a>
    </div>
</div>
{% endif %}
<div class="row">
    <div class="col">
        <div class="card">
            <ul class="list-group list-group-flush">
            {% if object_list %}
                {% for category in object_list %}
                    <li class="list-group-item">
                        <a href="{% url 'common:topics' category.pk %}"> {{ category.name }}</a>
                        {% if request.user.is_superuser %}
                        <div class="float-right">
                            <a href="{% url 'common:delete_category' category.pk %}" class="badge badge-danger">{% trans 'Delete' %}</a>
                            <a href="{% url 'common:update_category' category.pk %}" class="badge badge-info">{% trans 'Edit' %}</a>
                        </div>
                        {% endif %}
                    </li>
                {% endfor %}
            {% else %}
              <li class="list-group-item">{% trans 'No categories' %}</li>
            {% endif %}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

forum/forum/common/templates/common/category_update_form.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="d-none d-lg-block d-xl-block">
        {% bootstrap_button _("Update") button_type="submit" button_class="btn btn-primary" %}
        <a href="{% url 'common:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
    </div>
    <div class="d-lg-none d-xl-none">
        {% bootstrap_button _("Update") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
        <a href="{% url 'common:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
    </div>
</form>
{% endblock %}

forum/forum/common/templates/common/post_confirm_delete.html
{% extends 'common/base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<form class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>
       {{ _('Are you sure you want delete post?')}}
    </h1>
    <div class="card mt-3">
        <div class="card-body">
            <h5 class="card-title">{{ post.author.username }}</h5>
                <div class="float-right">
                    <a href="{% url 'common:delete_post' post.pk %}" class="btn btn-primary">{% trans 'Delete' %}</a>
                </div>
            <h6 class="card-subtitle mb-2 text-muted">{% trans 'Created at:' %}{{ post.created_at }} {% if post.updated_at %}| {% trans 'Updated at:' %}{{ post.updated_at }}{% endif %}</h6>
                <p class="card-text">{{ post.text }}</p>
        </div>
    </div>
    <div class="d-none d-lg-block d-xl-block">
        {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger" %}
        <a href="{% url 'common:index' %}" class="btn btn-light">{% trans 'Cancel' %}</a>
    </div>
    <div class="d-lg-none d-xl-none">
        {% bootstrap_button _("Delete") button_type="submit" button_class="btn btn-danger btn-lg btn-block" %}
        <a href="{% url 'common:index' %}" class="btn btn-light btn-lg btn-block">{% trans 'Cancel' %}</a>
    </div>
</form>
{% endblock %}

forum/forum/common/templates/common/post_list.html
{% extends 'common/base.html' %}

{% load bootstrap4 i18n %}

{% block content %}
<div class="row">
    <div class="col">
        <nav class="navbar navbar-light bg-light">
            <a class="navbar-brand">{{ topic.name }}</a>
        </nav>
        {% if object_list %}
        {% for post in page_obj %}
        <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">{{ post.author.username }}</h5>
                {% if request.user.id == post.author_id or request.user.is_superuser %}
                <div class="float-right">
                    <a href="{% url 'common:delete_post' post.pk %}" class="badge badge-danger">{% trans 'Delete' %}</a>
                </div>
                {% endif %}
                <h6 class="card-subtitle mb-2 text-muted">{% trans 'Created at: ' %}{{ post.created_at }} </h6>
                <p class="card-text">{{ post.text }}</p>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <li class="list-group-item">{% trans 'No posts' %} </li>
        {% endif %}
    </div>
</div>
{% if request.user.is_authenticated %}
{% if topic.active %}
<div class="row">
    <div class="col">
        <form class="form" method="post" action="{% url 'common:create_post' topic.pk %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
            </div>
        </form>
    </div>
</div>
{% endif %}
{% endif %}
<div class="row">
    <div class="col">
        <div class="pagination justify-content-center mt-4">
            {% bootstrap_pagination page_obj %}
        </div>
    </div>
</div>
{% endblock %}

forum/forum/common/templates/common/topic_block_form.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Edit") button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Edit") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

forum/forum/common/templates/common/topic_form.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% bootstrap_form form2 %}

            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Create") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

forum/forum/common/templates/common/topic_list.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col">
        <div class="card mt-4">
          <div class="card-header">
              <div class="float-left">
                {{ category.name }}
              </div>

            <div class="float-right">
                <a href="{% url 'common:create_topic' category.pk %}" class="badge badge-success">{% trans 'Create new topic' %}</a>
            </div>
          </div>
          <ul class="list-group list-group-flush">
            {% if page_obj %}
                {% for topic in page_obj %}

                    <li class="list-group-item">
                        <a href="{% url 'common:topic_posts' topic.pk %}">{{ topic.name }}</a>
                         {% if request.user.is_superuser %}

                            <div class="float-right">
                                 {% if topic.active %}
                                 <a href="{% url 'common:block_topic' topic.pk %}" class="badge badge-danger">{% trans 'Block' %}</a>
                                 <a href="{% url 'common:update_topic' topic.pk %}" class="badge badge-info">{% trans 'Edit' %}</a>
                                 {% endif %}
                                 {% if not topic.active %}
                                 <a href="{% url 'common:block_topic' topic.pk %}" class="badge badge-info">{% trans 'Activate' %}</a>
                                 {% endif %}
                            </div>

                        {% endif %}
                    </li>
                {% endfor %}
            {% else %}
              <li class="list-group-item">{% trans 'No topics' %}</li>
            {% endif %}
          </ul>
        </div>
        <div class="pagination justify-content-center mt-4">
            {% bootstrap_pagination page_obj %}
        </div>
    </div>
</div>

{% endblock %}

forum/forum/common/templates/common/topic_update_form.html
{% extends 'common/base.html' %}

{% load i18n bootstrap4 %}

{% block content %}
<div class="row">
    <div class="col">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="d-none d-lg-block d-xl-block">
                {% bootstrap_button _("Edit") button_type="submit" button_class="btn btn-primary" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning">{% trans 'Cancel' %}</a>
            </div>
            <div class="d-lg-none d-xl-none">
                {% bootstrap_button _("Edit") button_type="submit" button_class="btn btn-primary btn-lg btn-block" %}
                <a href="{% url 'common:index' %}" class="btn btn-warning btn-lg btn-block">{% trans 'Cancel' %}</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}